#!/bin/bash

if [ "$1" = "bootstrap" ]; then
  cp -va $(basename $0) ~/.ruby-commander
  exit  
fi

upstream_ruby_index=http://cache.ruby-lang.org/pub/ruby/
upstream_version_match='s/.*ruby-\(.*\)\.tar\.gz.*/\1/p'
upstream_ruby_versions=/tmp/available-ruby-versions

local_ruby_index=/opt
local_version_match='s/.*ruby-\(.*\).*/\1/p'
local_ruby_versions=/tmp/local-ruby-versions

_ruby_commander_update_indexes()
{
echo "Updating indexes... "
wget --quiet -O - $upstream_ruby_index  | sed -n $upstream_version_match > $upstream_ruby_versions
if [ $? -ne 0 ]; then
  echo "  Error updating upstream index."
else
  echo "  $(wc -l $upstream_ruby_versions) upstream versions."
fi
ls $local_ruby_index | sed -n $local_version_match > $local_ruby_versions
echo "  $(wc -l $local_ruby_versions) local versions."
return 0
}

_ruby_commander_completion()
{
  local cur=${COMP_WORDS[COMP_CWORD]}
  local prev=${COMP_WORDS[COMP_CWORD-1]}
  #echo -n "$COMP_CWORD "
  COMPREPLY=()
  case "$prev" in
    install)
      words=$(cat $upstream_ruby_versions | paste -s -)
      COMPREPLY=( $( compgen -W '$words' -- $cur ) )
    ;;
    use|uninstall)
      words=$(cat $local_ruby_versions | paste -s -)
      COMPREPLY=( $( compgen -W '$words' -- $cur ) )
    ;;
    *)
      COMPREPLY=()
      ;;
  esac
  if [ $COMP_CWORD -eq 1 ]; then
    COMPREPLY=( $( compgen -W 'install uninstall use update' -- $cur ) )
  fi
  return 0
}

function ruby-commander()
{
case $1 in
  install)
    tarball=ruby-$2.tar.gz
    cd /tmp
    curl $upstream_ruby_index$tarball
    tar zxvf $tarball
    cd --
    cd /tmp/ruby-$2
    ./configure --prefix=/$local_ruby_index/ruby-$2
    make
    sudo make install
    cd --
  ;;
  uninstall)
    directory=$local_ruby_index/ruby-$2
    rm -r $directory
  ;;
  use)
    directory=$local_ruby_index/ruby-$2
    NEW_PATH=$(echo $PATH | sed -n 's|\(/opt/ruby-[^/]*/bin:*\)||gp')
    NEW_PATH=$NEW_PATH:$directory/bin
    export PATH=$NEW_PATH
    gem env
  ;;
  update|*)
    _ruby_commander_update_indexes
  ;;
esac 
  return 0
}

complete -F _ruby_commander_completion ruby-commander
